### ISSUE TITLE
sph_ifs_combine_data does not respect "nocenter" for SCIENCE frames

### ISSUE THREAD

**Issue by DFEvans** [avigan/VLTPF#50]
Whilst the "nocenter" option is correctly adhered to for FLUX and CENTER frames in sph_ifs_combine_data, it is ignored for SCIENCE frames, as the "if nocenter/else" check is missing for SCIENCE frames.

**Comment by avigan** [comment]
Actually it does respect the `nocenter` option, but I guess the documentation is not clear and the code is slightly confusing. The `nocenter` option disables the **fine** centering, but it still shifts the images by an integer number of pixels to make sure that the data is roughly centered. For ths IFS it doesn't really matter because the data is always more or less centered, but for IRDIS it is more important because the center of the data is not so close to the image center. I will clarify the documentation.
