### ISSUE TITLE
Dependency versions

### ISSUE THREAD

**Issue by tomasstolker** [avigan/VLTPF#91]
I ran into an issue which seems to be related to the dependency versions.

With Python 3.7/3.8, I got the following error with an IRDIS imaging reduction:

`TypeError: Cannot parse "" as a Quantity. It does not start with a number.`

I could backtrace the error to the ``compute_angles`` function but I think that the actual problem is related to the dependency versions that I am using. When I changed to Python 3.6 and older dependency versions, the error did not occur.

Maybe it could be helpful to add a ``requirements.txt`` file with the (approximate) dependency versions that are supported by ``SPHERE``. Then one could for example install those versions within a virtual environment.

Thanks again for this great pipeline :)!

**Comment by avigan** [comment]
Hello @tomasstolker. I encountered this error at some point, and I implemented a fix. I cannot remember if the fix is already part of the public release or not. I fixed several issues in the pipeline today and I am going to release a new public version by the end of the week. Could you please re-test after that?

**Comment by tomasstolker** [comment]
Great, thanks! I installed the last version from Github and tested the first few steps of `ImagingReduction` with Python 3.6, 3.7, and 3.8. It runs without any problems!
